name: docs_mdpath
channels:

  - defaults
dependencies:
    # Base depends
  - python
  - pip
  - sphinx
  - sphinx_design
  - numpy
  - pandas
  - networkx
  - tqdm
  - biopython
  - nglview
  - pillow
  - mdanalysis
  - scipy
  - matplotlib
  - sklearn
  



    # Pip-only installs
  - pip:
    - -e ../

