name: docs_mdpath
channels:

  - defaults
dependencies:
    # Base depends
  - python
  - pip
  - sphinx
  - sphinx_design
  - numpy
  - pandas
  - networkx
  - tqdm
  - biopython
  - nglview
  - pillow
  - mdanalysis
  - scipy
  - matplotlib
  - sklearn
  




  - pip:
    - -e ../
    - mdpath
    - MDAnalysis>=2.7.0
    - pandas
    - scikit-learn
    - networkx
    - scipy
    - biopython
    - tqdm
    - seaborn
    - nglview
    - pillow
    - numpy-stl

